object Form1: TForm1
  Left = 642
  Top = 361
  AutoSize = True
  BorderStyle = bsNone
  Caption = 'Form1'
  ClientHeight = 354
  ClientWidth = 336
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
end
